apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: synergychat-api
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
